"""Secure credential storage and authenticated encrypted-backup APIs."""

from panopticon.secrets.adapters import (
    LinuxSecretServiceAdapter,
    MacOSKeychainAdapter,
    WindowsCredentialAdapter,
)
from panopticon.secrets.backup import SecureNonceSource, decrypt_backup, save_encrypted_backup
from panopticon.secrets.contracts import (
    BackendResult,
    BackupDecrypted,
    BackupDecryptRequest,
    BackupFailure,
    BackupMetadata,
    BackupResult,
    BackupSaved,
    BackupUnavailable,
    BackupWriteRequest,
    CapabilityResult,
    CapabilityStatus,
    KeyResult,
    KeyringAPI,
    KeyringDataError,
    KeyringUnavailable,
    NonceSource,
    OperationResult,
    PersistWriter,
    PlatformBackend,
    SecretHandle,
    SecretMaterialBackend,
    SecretStore,
    SecretUseError,
)
from panopticon.secrets.crypto import (
    AES_KEY_BYTES,
    ENVELOPE_ALGORITHM,
    ENVELOPE_VERSION,
    GCM_NONCE_BYTES,
    EncryptedBackupEnvelope,
    EncryptionRequest,
    EnvelopeError,
    InvalidTag,
    decrypt_envelope,
    encode_envelope,
    encrypt_envelope,
    parse_envelope,
)
from panopticon.secrets.keyring_backend import KeyringBridge, LazyKeyringAPI
from panopticon.secrets.memory import InMemorySecretStore

__all__ = [
    "AES_KEY_BYTES",
    "ENVELOPE_ALGORITHM",
    "ENVELOPE_VERSION",
    "GCM_NONCE_BYTES",
    "BackendResult",
    "BackupDecryptRequest",
    "BackupDecrypted",
    "BackupFailure",
    "BackupMetadata",
    "BackupResult",
    "BackupSaved",
    "BackupUnavailable",
    "BackupWriteRequest",
    "CapabilityResult",
    "CapabilityStatus",
    "EncryptedBackupEnvelope",
    "EncryptionRequest",
    "EnvelopeError",
    "InMemorySecretStore",
    "InvalidTag",
    "KeyResult",
    "KeyringAPI",
    "KeyringBridge",
    "KeyringDataError",
    "KeyringUnavailable",
    "LazyKeyringAPI",
    "LinuxSecretServiceAdapter",
    "MacOSKeychainAdapter",
    "NonceSource",
    "OperationResult",
    "PersistWriter",
    "PlatformBackend",
    "SecretHandle",
    "SecretMaterialBackend",
    "SecretStore",
    "SecretUseError",
    "SecureNonceSource",
    "WindowsCredentialAdapter",
    "decrypt_backup",
    "decrypt_envelope",
    "encode_envelope",
    "encrypt_envelope",
    "parse_envelope",
    "save_encrypted_backup",
]
